/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg = (uint32_t*)0x40020C14;

	uint32_t *pPortAModeReg = (uint32_t*)0x40020000;
	uint32_t *pPortAInReg = (uint32_t*)0x40020010;

	// Enable the clock for GPIOD and GPIOA peripherals in the AHB1ENR
	*pClkCtrlReg |= (1 << 3);
	*pClkCtrlReg |= (1 << 0);

	// Configure the mode of PD12 as output
	// Clear the 24th and 25th bit positions
	*pPortDModeReg &= ~(3 << 24);
	// Make 24th bit position as 1 (SET)
	*pPortDModeReg |= (1 << 24);

	// Configure the mode of PA0 as input
	*pPortAModeReg &= ~(3 << 0);

    /* Loop forever */
	for(;;) {
		// Read the status of the pin PA0
		uint8_t pinStatus = (uint8_t)(*pPortAInReg & 0x1);

		if (pinStatus) {
			// Turn on the LED
			*pPortDOutReg |= (1 << 12);
		} else {
			// Turn off the LED
			*pPortDOutReg &= ~(1 << 12);
		}
	}
}
