/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_AHB1ENR_t 	volatile *const pClkCtrlReg		= (RCC_AHB1ENR_t*)0x40023830;
	GPIOx_MODE_t 	volatile *const pPortDModeReg	= (GPIOx_MODE_t*)0x40020C00;
	GPIOx_ODR_t 	volatile *const pPortDOutReg	= (GPIOx_ODR_t*)0x40020C14;

	// Enable the clock for the GPIOD peripheral in the AHB1ENR (SET the 3rd bit position)
	pClkCtrlReg->gpiod_en = 1;

	// Configure the mode of the IO pin as output
	pPortDModeReg->pin_12 = 1;

	/* Loop forever */
	for(;;) {
		// Set 12th bit of the output data register to make I/O pin-12 as HIGH
		pPortDOutReg->pin_12 = 1;

		// Introduce small human observable delay
		for(uint32_t i = 0; i < 300000; i++);

		// Turn off the LED
		pPortDOutReg->pin_12 = 0;
		for(uint32_t i = 0; i < 300000; i++);
	}
}
